import { escapeHtml } from './escape';

export interface HtmlDocumentOptions {
  title: string;
  body: string;
  generatedAt?: Date | string;
  extraStyles?: string;
}

export function renderHtmlDocument(options: HtmlDocumentOptions): string {
  const generatedAt = dateFromInput(options.generatedAt);
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(options.title)}</title>
  <style>
${baseStyles()}
${options.extraStyles ?? ''}
  </style>
</head>
<body>
${options.body}
  <footer>
    <p>Generated by <a href="https://github.com/raulradulescu/arael">Arael</a> - Reverse Engineering Assistant</p>
    <p class="footer-meta">Timestamp: ${escapeHtml(generatedAt.toISOString())}</p>
  </footer>
  <script>
${baseScript()}
  </script>
</body>
</html>`;
}

export function formatGeneratedDate(value?: Date | string): string {
  return dateFromInput(value).toLocaleString('en-US', {
    dateStyle: 'medium',
    timeStyle: 'short'
  });
}

function dateFromInput(value?: Date | string): Date {
  if (value instanceof Date) {
    return value;
  }
  if (typeof value === 'string') {
    const parsed = new Date(value);
    if (!Number.isNaN(parsed.getTime())) {
      return parsed;
    }
  }
  return new Date();
}

function baseStyles(): string {
  return `
    :root {
      --bg-primary: #0d1117;
      --bg-secondary: #161b22;
      --bg-tertiary: #21262d;
      --border: #30363d;
      --text: #e6edf3;
      --text-muted: #8b949e;
      --accent: #58a6ff;
      --accent-hover: #79b8ff;
      --danger: #f85149;
      --warning: #d29922;
      --success: #3fb950;
      --purple: #a371f7;
      --pink: #db61a2;
      --gradient-start: #58a6ff;
      --gradient-end: #a371f7;
    }
    @media (prefers-color-scheme: light) {
      :root {
        --bg-primary: #f6f8fa;
        --bg-secondary: #ffffff;
        --bg-tertiary: #f0f3f6;
        --border: #d0d7de;
        --text: #24292f;
        --text-muted: #57606a;
        --accent: #0969da;
        --accent-hover: #0550ae;
        --danger: #cf222e;
        --warning: #9a6700;
        --success: #1a7f37;
        --purple: #8250df;
        --pink: #bf3989;
      }
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif;
      background: var(--bg-primary);
      color: var(--text);
      line-height: 1.6;
      min-height: 100vh;
    }
    a { color: var(--accent); text-decoration: none; }
    a:hover { text-decoration: underline; }
    .header {
      background: linear-gradient(135deg, var(--bg-secondary) 0%, var(--bg-tertiary) 100%);
      border-bottom: 1px solid var(--border);
      padding: 2rem;
      margin-bottom: 2rem;
    }
    .header-content {
      max-width: 1400px;
      margin: 0 auto;
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      flex-wrap: wrap;
      gap: 1rem;
    }
    .header h1 {
      margin: 0;
      font-size: 1.75rem;
      font-weight: 600;
      background: linear-gradient(90deg, var(--gradient-start), var(--gradient-end));
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;
    }
    .header-meta {
      display: flex;
      flex-wrap: wrap;
      gap: 1rem 1.5rem;
      margin-top: 0.5rem;
      color: var(--text-muted);
      font-size: 0.875rem;
    }
    .container { max-width: 1400px; margin: 0 auto; padding: 0 2rem 2rem; }
    .section { margin-bottom: 2rem; }
    .section-header {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      margin-bottom: 1rem;
      padding-bottom: 0.5rem;
      border-bottom: 1px solid var(--border);
    }
    .section-header h2 {
      margin: 0;
      font-size: 1.25rem;
      font-weight: 600;
      color: var(--text);
    }
    .section-icon {
      width: 24px;
      height: 24px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      background: var(--bg-tertiary);
      border-radius: 6px;
      font-size: 0.875rem;
    }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1rem; }
    .grid-2 { grid-template-columns: repeat(auto-fit, minmax(360px, 1fr)); }
    .card {
      background: var(--bg-secondary);
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 1.25rem;
    }
    .card-title {
      font-size: 0.75rem;
      font-weight: 700;
      color: var(--text-muted);
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
    .card-value {
      margin-top: 0.5rem;
      font-size: 2rem;
      font-weight: 700;
      color: var(--accent);
      line-height: 1;
    }
    .card-label { font-size: 0.8rem; color: var(--text-muted); margin-top: 0.5rem; }
    .info-row {
      display: flex;
      justify-content: space-between;
      gap: 1rem;
      padding: 0.5rem 0;
      border-bottom: 1px solid var(--border);
    }
    .info-row:last-child { border-bottom: none; }
    .info-label { color: var(--text-muted); font-size: 0.875rem; }
    .info-value { font-weight: 500; font-family: "SF Mono", Consolas, monospace; font-size: 0.875rem; text-align: right; }
    .hash-value, code, .mono {
      font-family: "SF Mono", Consolas, monospace;
      font-size: 0.8rem;
      background: var(--bg-tertiary);
      padding: 0.2rem 0.4rem;
      border-radius: 4px;
      color: var(--accent);
      word-break: break-all;
    }
    .toolbar {
      display: flex;
      align-items: center;
      justify-content: space-between;
      flex-wrap: wrap;
      gap: 0.75rem;
      margin-bottom: 0.75rem;
    }
    .toolbar-group { display: flex; align-items: center; flex-wrap: wrap; gap: 0.75rem; }
    .search-box input {
      min-width: 260px;
      max-width: 100%;
      background: var(--bg-secondary);
      border: 1px solid var(--border);
      color: var(--text);
      border-radius: 6px;
      padding: 0.5rem 0.75rem;
      font: inherit;
    }
    .toggle {
      display: inline-flex;
      align-items: center;
      gap: 0.4rem;
      color: var(--text-muted);
      font-size: 0.875rem;
      user-select: none;
    }
    .table-wrapper {
      background: var(--bg-secondary);
      border: 1px solid var(--border);
      border-radius: 8px;
      overflow: auto;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 0.875rem;
    }
    th {
      text-align: left;
      padding: 0.75rem 1rem;
      background: var(--bg-tertiary);
      color: var(--text-muted);
      font-weight: 700;
      font-size: 0.75rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      border-bottom: 1px solid var(--border);
      white-space: nowrap;
    }
    th[data-sortable="true"] { cursor: pointer; }
    th[data-sortable="true"]::after { content: " \\2195"; opacity: 0.45; }
    td {
      padding: 0.75rem 1rem;
      border-bottom: 1px solid var(--border);
      vertical-align: middle;
    }
    tr:last-child td { border-bottom: none; }
    tr:hover td { background: var(--bg-tertiary); }
    .badge {
      display: inline-flex;
      align-items: center;
      gap: 0.35rem;
      padding: 0.25rem 0.5rem;
      border-radius: 4px;
      font-size: 0.72rem;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.025em;
      border: 1px solid transparent;
      white-space: nowrap;
    }
    .badge-success { background: rgba(63, 185, 80, 0.15); color: var(--success); border-color: rgba(63, 185, 80, 0.45); }
    .badge-warn { background: rgba(210, 153, 34, 0.15); color: var(--warning); border-color: rgba(210, 153, 34, 0.45); }
    .badge-danger { background: rgba(248, 81, 73, 0.15); color: var(--danger); border-color: rgba(248, 81, 73, 0.45); }
    .badge-muted { background: rgba(139, 148, 158, 0.15); color: var(--text-muted); border-color: rgba(139, 148, 158, 0.35); }
    .badge-accent { background: rgba(88, 166, 255, 0.15); color: var(--accent); border-color: rgba(88, 166, 255, 0.45); }
    .tag {
      display: inline-flex;
      align-items: center;
      padding: 0.25rem 0.5rem;
      border-radius: 4px;
      font-size: 0.7rem;
      font-weight: 700;
      margin: 0.125rem;
      text-transform: uppercase;
      letter-spacing: 0.025em;
      background: rgba(88, 166, 255, 0.15);
      color: var(--accent);
    }
    .tag-danger { background: rgba(248, 81, 73, 0.15); color: var(--danger); }
    .tag-warn { background: rgba(210, 153, 34, 0.15); color: var(--warning); }
    .tag-success { background: rgba(63, 185, 80, 0.15); color: var(--success); }
    .bar {
      position: relative;
      display: inline-flex;
      align-items: center;
      min-width: 110px;
      height: 1.35rem;
      background: var(--bg-tertiary);
      border: 1px solid var(--border);
      border-radius: 999px;
      overflow: hidden;
      vertical-align: middle;
    }
    .bar-fill {
      position: absolute;
      inset: 0 auto 0 0;
      background: linear-gradient(90deg, var(--success), var(--accent));
    }
    .bar-label {
      position: relative;
      z-index: 1;
      width: 100%;
      text-align: center;
      font-size: 0.75rem;
      font-weight: 700;
      color: var(--text);
    }
    .icon-button {
      margin-left: 0.5rem;
      border: 1px solid var(--border);
      background: var(--bg-tertiary);
      color: var(--text-muted);
      border-radius: 5px;
      padding: 0.2rem 0.45rem;
      font-size: 0.7rem;
      cursor: pointer;
    }
    .icon-button:hover { border-color: var(--accent); color: var(--accent); }
    .collapsible {
      background: var(--bg-secondary);
      border: 1px solid var(--border);
      border-radius: 8px;
      margin-bottom: 0.75rem;
      overflow: hidden;
    }
    .collapsible summary {
      cursor: pointer;
      padding: 0.85rem 1rem;
      font-weight: 700;
      color: var(--text);
      background: var(--bg-tertiary);
    }
    .collapsible-body { padding: 1rem; }
    .muted { color: var(--text-muted); }
    .danger { color: var(--danger); }
    .warn { color: var(--warning); }
    .success { color: var(--success); }
    .nowrap { white-space: nowrap; }
    .sr-only {
      position: absolute;
      width: 1px;
      height: 1px;
      padding: 0;
      margin: -1px;
      overflow: hidden;
      clip: rect(0, 0, 0, 0);
      white-space: nowrap;
      border: 0;
    }
    footer {
      margin-top: 3rem;
      padding: 2rem;
      text-align: center;
      border-top: 1px solid var(--border);
      color: var(--text-muted);
      font-size: 0.875rem;
    }
    .footer-meta { margin-top: 0.5rem; font-size: 0.75rem; }
    @media (max-width: 768px) {
      .header-content { flex-direction: column; }
      .header-meta { flex-direction: column; gap: 0.5rem; }
      .grid, .grid-2 { grid-template-columns: 1fr; }
      .container { padding: 0 1rem 1rem; }
      .search-box input { min-width: 0; width: 100%; }
      .toolbar { align-items: stretch; }
      .toolbar-group { width: 100%; }
    }
  `;
}

function baseScript(): string {
  return `
    (function () {
      function textFor(row) {
        return row.textContent.toLowerCase();
      }
      function applyFilters(tableId) {
        var table = document.getElementById(tableId);
        if (!table) return;
        var searchInputs = document.querySelectorAll('[data-search-target="' + tableId + '"]');
        var solvedToggles = document.querySelectorAll('[data-solved-toggle="' + tableId + '"]');
        var query = '';
        searchInputs.forEach(function (input) {
          query += ' ' + String(input.value || '').toLowerCase();
        });
        query = query.trim();
        var solvedOnly = false;
        solvedToggles.forEach(function (toggle) {
          solvedOnly = solvedOnly || toggle.checked;
        });
        table.querySelectorAll('tbody tr').forEach(function (row) {
          var matchesQuery = !query || textFor(row).indexOf(query) !== -1;
          var matchesSolved = !solvedOnly || row.getAttribute('data-solved') === 'true';
          row.style.display = matchesQuery && matchesSolved ? '' : 'none';
        });
      }
      document.querySelectorAll('[data-search-target]').forEach(function (input) {
        input.addEventListener('input', function () {
          applyFilters(input.getAttribute('data-search-target'));
        });
      });
      document.querySelectorAll('[data-solved-toggle]').forEach(function (input) {
        input.addEventListener('change', function () {
          applyFilters(input.getAttribute('data-solved-toggle'));
        });
      });
      document.querySelectorAll('th[data-sortable="true"]').forEach(function (th) {
        th.addEventListener('click', function () {
          var table = th.closest('table');
          if (!table || !table.tBodies.length) return;
          var index = Array.prototype.indexOf.call(th.parentNode.children, th);
          var direction = th.getAttribute('data-sort-dir') === 'asc' ? 'desc' : 'asc';
          th.parentNode.querySelectorAll('th').forEach(function (other) {
            other.removeAttribute('data-sort-dir');
          });
          th.setAttribute('data-sort-dir', direction);
          var rows = Array.from(table.tBodies[0].rows);
          rows.sort(function (left, right) {
            var leftText = (left.cells[index] && left.cells[index].getAttribute('data-sort-value')) || (left.cells[index] && left.cells[index].textContent) || '';
            var rightText = (right.cells[index] && right.cells[index].getAttribute('data-sort-value')) || (right.cells[index] && right.cells[index].textContent) || '';
            var leftNum = Number(String(leftText).replace(/[^0-9.+-]/g, ''));
            var rightNum = Number(String(rightText).replace(/[^0-9.+-]/g, ''));
            var result = Number.isFinite(leftNum) && Number.isFinite(rightNum)
              ? leftNum - rightNum
              : String(leftText).localeCompare(String(rightText), undefined, { numeric: true, sensitivity: 'base' });
            return direction === 'asc' ? result : -result;
          });
          rows.forEach(function (row) {
            table.tBodies[0].appendChild(row);
          });
        });
      });
      document.querySelectorAll('[data-copy]').forEach(function (button) {
        button.addEventListener('click', function () {
          var text = button.getAttribute('data-copy') || '';
          var done = function () {
            var previous = button.textContent;
            button.textContent = 'Copied';
            setTimeout(function () { button.textContent = previous; }, 1000);
          };
          if (navigator.clipboard && navigator.clipboard.writeText) {
            navigator.clipboard.writeText(text).then(done).catch(function () {});
          } else {
            var area = document.createElement('textarea');
            area.value = text;
            document.body.appendChild(area);
            area.select();
            try { document.execCommand('copy'); done(); } catch (error) {}
            document.body.removeChild(area);
          }
        });
      });
    }());
  `;
}
